In [14]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi

from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')

## Single Qubit Gates

the accessible gates are
- u gates
- identity
- pauli
- clifford
- C3 gates
- standard rotation gates

$$u_3(\theta, \phi, \lambda) = U = \begin{pmatrix}
\cos(\theta/2) & -e^{i\lambda}\sin(\theta/2) \\
e^{i\phi}\sin(\theta/2) & e^{i\lambda+i\phi}\cos(\theta/2) 
\end{pmatrix}$$

In [3]:
singleq = QuantumRegister(1)

In [6]:
#ugates - general unitary using u3 gate
# in particular, u2(\phi, \lambda) = u3(pi/2, \phi, \lambda), u1(\lambda) = u3(0, 0, \lambda)

qcu = QuantumCircuit(singleq)
qcu.u3(pi/2, pi/2, pi/2, singleq)
qcu.draw()

In [10]:
job = execute(qcu, backend)
job.result().get_unitary(qcu, decimals = 3)

array([[ 0.707+0.j   ,  0.   -0.707j],
       [ 0.   +0.707j, -0.707+0.j   ]])

In [12]:
# identity
qci = QuantumCircuit(singleq)
qci.iden(singleq)
qci.draw()

In [16]:
job = execute(qci, backend)
job.result().get_unitary(qci, decimals=3)

array([[1.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j]])

In [32]:
## Paulis
qci = QuantumCircuit(singleq)

In [28]:
qci.x(singleq)
qci.draw()

In [20]:
job = execute(qci, backend)
job.result().get_unitary(qci, decimals = 3)

array([[0.+0.j, 1.+0.j],
       [1.+0.j, 0.+0.j]])

In [27]:
qci.y(singleq)
qci.draw()
job = execute(qci, backend)
job.result().get_unitary(qci, decimals = 3)

array([[0.+0.j, 0.-1.j],
       [0.+1.j, 0.+0.j]])

In [31]:
qci.z(singleq)
job = execute(qci, backend)
job.result().get_unitary(qci, decimals = 3)

array([[ 1.+0.j,  0.+0.j],
       [ 0.+0.j, -1.+0.j]])

## Arbitrary initialization


In [35]:
from math import *

In [44]:
desired_vec = [
    
    complex(1, 1)/sqrt(10),
    complex(1, 0)*math.sqrt(2)/sqrt(10), 
    complex(1, 1)/sqrt(10),
    0, 
    0, 
    complex(1, 1)/sqrt(10),
    complex(1, 0)*sqrt(2)/sqrt(10),
    0
    ]

In [71]:
qc = QuantumCircuit(q)

In [72]:
qc.initialize(desired_vec, q)
qc.draw()

In [73]:
# Useful additional packages 
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from math import pi

from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, execute
from qiskit.tools.visualization import circuit_drawer
from qiskit.quantum_info import state_fidelity
from qiskit import BasicAer

backend = BasicAer.get_backend('unitary_simulator')